"""Add phone_number and complaint to Appointment

Revision ID: ed63b245a558
Revises: 56d364f75f14
Create Date: 2026-07-07 19:56:10.791828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed63b245a558'
down_revision = '56d364f75f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('complaint', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('complaint')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
